system:
  logLevel: DEBUG
  logfile: /var/log/system.log
  # announce only if you have one virtual ts3 server. won't work otherwise.
  announceServer: True
  serverName: Ts3Proxy
  maxUsers: 100
ts3server:
  enabled: True
  relayPort: 9987
  remoteAddr: 51.38.119.22
  remotePort: 9987
  #relayAddress: 0.0.0.0
  # relayPort:remoteAddress:remotePort
  # multiple servers splitted by ","
  #servers: "9987:127.0.0.1:9987"
  blacklist: blacklist.txt
  whitelist: whitelist.txt
ts3FileTransfer:
  enabled: True
  # relayAddress: 0.0.0.0
  relayPort: 33033
  remoteAddr: 51.38.119.22
  remotePort: 33033
  blacklist: blacklist.txt
  whitelist: whitelist.txt
ts3ServerQuery:
  enabled: True
  # relayAddress: 0.0.0.0
  relayPort: 44044
  remoteAddr: 51.38.119.22
  remotePort: 44044
  blacklist: blacklist.txt
  whitelist: whitelist.txt
